language: node_js
node_js: stable
before_install:
- openssl aes-256-cbc -K $encrypted_22d2942debff_key -iv $encrypted_22d2942debff_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- ssh travis@lilywang.cn -p 12345 'cd ~/projects/personal-web/ && git pull'